spring.application.name=inventoryservice

# accessable only through local machine 
server.address=127.0.0.1

#logging.level.root=DEBUG
#spring.datasource.url=jdbc:mysql://localhost:3306/ticketing?createDatabaseIfNotExist=true ticketing is already created via docker-compose
spring.datasource.url=jdbc:mysql://localhost:3306/ticketing
spring.jpa.hibernate.ddl-auto=none
spring.datasource.username=myuser
spring.datasource.password=secret
# spring.sql.init.mode=always
# spring.sql.init.data-locations=classpath:init.sql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#spring.flyway.enabled=false


