server:
  port: 8082

spring:
  application:
    name: apigateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:8091/realms/ticketing-security-realm
#  Gateway Routing Logic in YAML below
  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 5s 

      # mvc:
      #   routes:
      #     - id: booking-service
      #       uri: http://localhost:8081
      #       predicates:
      #         - Path=/api/v1/booking
      #         - Method=POST
      #       filters:
      #         - name: CircuitBreaker
      #           args:
      #             name: bookingServiceCircuitBreaker
      #             fallbackUri: forward:/fallbackRoute

      #     - id: inventory-service
      #       uri: http://localhost:8080
      #       predicates:
      #         - Path=/api/v1/inventory/**
      #         - Method=GET,PUT
      #       filters:
      #         - name: CircuitBreaker
      #           args:
      #             name: inventoryServiceCircuitBreaker
      #             fallbackUri: forward:/fallbackRoute

keycloak:
  auth:
    jwk-set-uri: http://127.0.0.1:8091/realms/ticketing-security-realm/protocol/openid-connect/certs

#Actuator
management.health.circuitbreakers.enabled: true

#Exposing all endpoints
management.endpoints.web.exposure.include: '*'
management.endpoint.health.show-details: always